### ISSUE TITLE
Updated TSM and Ace3 got error

### ISSUE THREAD

**Issue by Agamemnon128** [mikepauer/Carbonite.Info#3]
Message: Interface/AddOns/Carbonite.Info/NxInfo.lua:280: attempt to call global 'UnitMana' (a nil value)
Time: Wed Dec  7 13:12:26 2022
Count: 1
Stack: Interface/AddOns/Carbonite.Info/NxInfo.lua:280: attempt to call global 'UnitMana' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `UnitMana'
[string "@Interface/AddOns/Carbonite.Info/NxInfo.lua"]:280: in function `OnTimer'
[string "@Interface/AddOns/Carbonite.Info/NxInfo.lua"]:252: in function `Init'
[string "@Interface/AddOns/Carbonite.Info/NxInfo.lua"]:156: in function `func'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:57: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: 

Happens without TSM as well

**Comment by IrcDirk** [comment]
Same here, please update, line 280 doesn't have ``UnitMana``.
